<a href="https://colab.research.google.com/github/SrijaGuduru/SrijaGuduru/blob/main/IRS_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import numpy as np
import pandas as pd
import re
import string

In [ ]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'
#df = pd.read_csv(path + 'datasets.csv')

df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")  # Use '\t' if it's tab-separated

In [ ]:
df.head()

asin,reviewText,overall,category,summary
0  B000K2PJ4K,Great product and price!,5.0,AMAZON...
1  B000K2PJ4K,Waaay too small. Will use for futur...
2  B000K2PJ4K,Stays vibrant after many washes,5.0...
3  B000K2PJ4K,Stays vibrant after many washes,5.0...
4  B000K2PJ4K,My son really likes the pink. Ones ...

In [ ]:
text = df["asin,reviewText,overall,category,summary"].str.lower()
text

0       b000k2pj4k,great product and price!,5.0,amazon...
1       b000k2pj4k,waaay too small. will use for futur...
2       b000k2pj4k,stays vibrant after many washes,5.0...
3       b000k2pj4k,stays vibrant after many washes,5.0...
4       b000k2pj4k,my son really likes the pink. ones ...
                              ...                        
3314    b005ago4lu,perfect fit!,5.0,amazon_fashion_5,f...
3315    b005ago4lu,my favorite cross trainers!,5.0,ama...
3316    b005ago4lu,love them fit perfect,5.0,amazon_fa...
3317    b005ago4lu,favorite nike shoe ever! the flex s...
3318    b005ago4lu,"i wear these everyday to work, the...
Name: asin,reviewText,overall,category,summary, Length: 3319, dtype: object

In [ ]:
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))
text

0       B000K2PJ4KGreat product and price50AMAZONFASHI...
1       B000K2PJ4KWaaay too small Will use for futur c...
2       B000K2PJ4KStays vibrant after many washes50AMA...
3       B000K2PJ4KStays vibrant after many washes50AMA...
4       B000K2PJ4KMy son really likes the pink Ones wh...
                              ...                        
3314      B005AGO4LUPerfect fit50AMAZONFASHION5Five Stars
3315    B005AGO4LUMy favorite cross trainers50AMAZONFA...
3316    B005AGO4LULove them fit perfect50AMAZONFASHION...
3317    B005AGO4LUFavorite Nike shoe ever The flex sol...
3318    B005AGO4LUI wear these everyday to work the gy...
Name: asin,reviewText,overall,category,summary, Length: 3319, dtype: object

In [ ]:
import os
import numpy as np
import pandas as pd
import re
import string

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '',text)  # Added regex=True for clarity
text                                                                                       # and to avoid future warnings


Mounted at /content/drive


0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
3314   NaN
3315   NaN
3316   NaN
3317   NaN
3318   NaN
Name: asin,reviewText,overall,category,summary, Length: 3319, dtype: float64

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)  # Added regex=True for clarity
                                                                                       # and to avoid future warnings
text = df["asin,reviewText,overall,category,summary"]
tokens=word_tokenize(text[0]) # Pass a single string to word_tokenize
tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Mounted at /content/drive


['B000K2PJ4K',
 ',',
 'Great',
 'product',
 'and',
 'price',
 '!',
 ',5.0',
 ',',
 'AMAZON_FASHION_5',
 ',',
 'Five',
 'Stars']

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)  # Added regex=True for clarity
                                                                                       # and to avoid future warnings
#text = df["asin,reviewText,overall,category,summary"] #This line is not needed.
#tokens=word_tokenize(text[0]) # Pass a single string to word_tokenize #This line is not needed.
#text = df["asin,reviewText,overall,category,summary"] #This line is not needed.
# Iterate over each value in the Series and apply sentence tokenization
sentences = []
for value in df["asin,reviewText,overall,category,summary"]:
    sentences.extend(sent_tokenize(value))

sentences


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


Mounted at /content/drive


['B000K2PJ4K,Great product and price!,5.0,AMAZON_FASHION_5,Five Stars',
 'B000K2PJ4K,Waaay too small.',
 'Will use for futur children!,3.0,AMAZON_FASHION_5,Oops!',
 'B000K2PJ4K,Stays vibrant after many washes,5.0,AMAZON_FASHION_5,Great',
 'B000K2PJ4K,Stays vibrant after many washes,5.0,AMAZON_FASHION_5,Good',
 'B000K2PJ4K,My son really likes the pink.',
 'Ones which I was nervous about,5.0,AMAZON_FASHION_5,Great',
 'B000K2PJ4K,Waaay too small.',
 'Will use for future child.,3.0,AMAZON_FASHION_5,Oops!',
 'B000KPIHQ4,Relieved my Plantar Fascitis for 3 Days.',
 'Then the unbearable pain returned in full force.',
 'These were recommended by my Podiatrist.,2.0,AMAZON_FASHION_5,These were recommended by my Podiatrist',
 'B000KPIHQ4,"This is my 6th pair and they are the best thing ever for my plantar fasciitis and resultant neuromas.',
 'Unfortunately, the ones I ordered from SmartDestination must be seconds as they kill my feet.',
 'The hard plastic insert rubs on the outside edges of my fee

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords') # Download the stopwords dataset
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)  # Added regex=True for clarity
                                                                                       # and to avoid future warnings
text = df["asin,reviewText,overall,category,summary"]
#tokens=word_tokenize(text[0]) # Pass a single string to word_tokenize #This is not needed for the filtering


filtered_words_list = [] #Create a list to hold the filtered words for each row.

for row in text:  #Iterate over each row in the 'text' Series
    words = word_tokenize(row) #Tokenize the words in the current row
    filtered_words = [word for word in words if word.lower() not in stopwords.words("english")] #Filter out the stop words.
    filtered_words_list.append(" ".join(filtered_words)) # Append the filtered sentence back into the list.

filtered_words_series = pd.Series(filtered_words_list) # Convert the list back to a Series.
print(filtered_words_series)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Mounted at /content/drive
0       B000K2PJ4K , Great product price ! ,5.0 , AMAZ...
1       B000K2PJ4K , Waaay small . use futur children ...
2       B000K2PJ4K , Stays vibrant many washes,5.0 , A...
3       B000K2PJ4K , Stays vibrant many washes,5.0 , A...
4       B000K2PJ4K , son really likes pink . Ones nerv...
                              ...                        
3314    B005AGO4LU , Perfect fit ! ,5.0 , AMAZON_FASHI...
3315    B005AGO4LU , favorite cross trainers ! ,5.0 , ...
3316    B005AGO4LU , Love fit perfect,5.0 , AMAZON_FAS...
3317    B005AGO4LU , Favorite Nike shoe ever ! flex so...
3318    B005AGO4LU , '' wear everyday work , gym , etc...
Length: 3319, dtype: object


In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords') # Download the stopwords dataset
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)  # Added regex=True for clarity
                                                                                       # and to avoid future warnings
text = df["asin,reviewText,overall,category,summary"]
#tokens=word_tokenize(text[0]) # Pass a single string to word_tokenize #This is not needed for the filtering


filtered_words_list = [] #Create a list to hold the filtered words for each row.

for row in text:  #Iterate over each row in the 'text' Series
    words = word_tokenize(row) #Tokenize the words in the current row
    filtered_words = [word for word in words if word.lower() not in stopwords.words("english")] #Filter out the stop words.
    filtered_words_list.append(" ".join(filtered_words)) # Append the filtered sentence back into the list.

filtered_words_series = pd.Series(filtered_words_list) # Convert the list back to a Series.

stemmer = PorterStemmer()

stemmed_words = [stemmer.stem(word) for word in words]
print(stemmed_words)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Mounted at /content/drive
['b005ago4lu', ',', "''", 'i', 'wear', 'these', 'everyday', 'to', 'work', ',', 'the', 'gym', ',', 'etc', '.', '``', ',5.0', ',', 'amazon_fashion_5', ',', 'five', 'star']


In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords') # Download the stopwords dataset
nltk.download('wordnet') # Download the wordnet dataset
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# Import wordnet
from nltk.corpus import wordnet

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)
  # Added regex=True for clarity
lemmatizer = WordNetLemmatizer()
                                                                                       # and to avoid future warnings
words = df["asin,reviewText,overall,category,summary"]
#tokens=word_tokenize(text[0]) # Pass a single string to word_tokenize #This is not needed for the filtering
lemmatized_words = [lemmatizer.lemmatize(word, wordnet.VERB) for word in words] # Now wordnet is defined.
print(lemmatized_words)



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Mounted at /content/drive
['B000K2PJ4K,Great product and price!,5.0,AMAZON_FASHION_5,Five Stars', 'B000K2PJ4K,Waaay too small. Will use for futur children!,3.0,AMAZON_FASHION_5,Oops!', 'B000K2PJ4K,Stays vibrant after many washes,5.0,AMAZON_FASHION_5,Great', 'B000K2PJ4K,Stays vibrant after many washes,5.0,AMAZON_FASHION_5,Good', 'B000K2PJ4K,My son really likes the pink. Ones which I was nervous about,5.0,AMAZON_FASHION_5,Great', 'B000K2PJ4K,Waaay too small. Will use for future child.,3.0,AMAZON_FASHION_5,Oops!', 'B000KPIHQ4,Relieved my Plantar Fascitis for 3 Days. Then the unbearable pain returned in full force. These were recommended by my Podiatrist.,2.0,AMAZON_FASHION_5,These were recommended by my Podiatrist', 'B000KPIHQ4,"This is my 6th pair and they are the best thing ever for my plantar fasciitis and resultant neuromas. Unfortunately, the ones I ordered from SmartDestination must be seconds as they kill my feet. The hard plastic insert rubs on the outside edges of my feet. I am u

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords') # Download the stopwords dataset
nltk.download('wordnet') # Download the wordnet dataset
nltk.download('averaged_perceptron_tagger') # Download the tagger resource.
# Download the english specific resource for the pos_tag function.
nltk.download('averaged_perceptron_tagger_eng') #This is the change.
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# Import wordnet
from nltk.corpus import wordnet
from nltk import pos_tag

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)
  # Added regex=True for clarity

                                                                                       # and to avoid future warnings
# Instead of assigning the entire column, you should iterate over the column and tokenize each element
#words = df["asin,reviewText,overall,category,summary"] # This is a series.

# Create an empty list to store the tokens
all_tokens = []

# Iterate through each row of the 'asin,reviewText,overall,category,summary' column
for index in df.index:
    text = df.loc[index, "asin,reviewText,overall,category,summary"]  # Get the text for the current row
    tokens = word_tokenize(text)  # Tokenize the text for the current row
    all_tokens.extend(tokens)  # Add the tokens to the list
# Now all_tokens should have a tokenized list of all data in your column, and you can continue with pos tagging.

pos_tags = pos_tag(all_tokens)
print(pos_tags)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


Mounted at /content/drive
[('B000K2PJ4K', 'NNP'), (',', ','), ('Great', 'NNP'), ('product', 'NN'), ('and', 'CC'), ('price', 'NN'), ('!', '.'), (',5.0', 'NN'), (',', ','), ('AMAZON_FASHION_5', 'NNP'), (',', ','), ('Five', 'CD'), ('Stars', 'NNP'), ('B000K2PJ4K', 'NNP'), (',', ','), ('Waaay', 'NNP'), ('too', 'RB'), ('small', 'JJ'), ('.', '.'), ('Will', 'MD'), ('use', 'VB'), ('for', 'IN'), ('futur', 'JJ'), ('children', 'NNS'), ('!', '.'), (',3.0', 'NN'), (',', ','), ('AMAZON_FASHION_5', 'NNP'), (',', ','), ('Oops', 'NNP'), ('!', '.'), ('B000K2PJ4K', 'NNP'), (',', ','), ('Stays', 'NNP'), ('vibrant', 'VBP'), ('after', 'IN'), ('many', 'JJ'), ('washes,5.0', 'NN'), (',', ','), ('AMAZON_FASHION_5', 'NNP'), (',', ','), ('Great', 'NNP'), ('B000K2PJ4K', 'NNP'), (',', ','), ('Stays', 'NNP'), ('vibrant', 'VBP'), ('after', 'IN'), ('many', 'JJ'), ('washes,5.0', 'NN'), (',', ','), ('AMAZON_FASHION_5', 'NNP'), (',', ','), ('Good', 'NNP'), ('B000K2PJ4K', 'NNP'), (',', ','), ('My', 'NNP'), ('son', 'NN'), (

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords') # Download the stopwords dataset
nltk.download('wordnet') # Download the wordnet dataset
nltk.download('averaged_perceptron_tagger') # Download the tagger resource.
# Download the english specific resource for the pos_tag function.
nltk.download('averaged_perceptron_tagger_eng') #This is the change.
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# Import wordnet
from nltk.corpus import wordnet
from nltk import pos_tag
import spacy

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)
  # Added regex=True for clarity

                                                                                       # and to avoid future warnings

nlp = spacy.load("en_core_web_sm")
#text = df["asin,reviewText,overall,category,summary"] #This was the error, it was passing a Series.
# Instead of passing the entire column, iterate over the column and process each element individually
for index in df.index:
    text = df.loc[index, "asin,reviewText,overall,category,summary"]  # Get the text for the current row
    doc = nlp(text)  # Process the text for the current row
    for ent in doc.ents:
        print(ent.text, ent.label_)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


Mounted at /content/drive
Waaay GPE
Stays PERSON
Stays PERSON
washes,5.0,AMAZON_FASHION_5,Good PERSON
Waaay GPE
Plantar Fascitis PERSON
3 Days DATE
6th ORDINAL
SmartDestination WORK_OF_ART
one day DATE
B000KPIHQ4,We PERSON
years DATE
257lbs CARDINAL
every 3 months DATE
B000KPIHQ4,These NORP
,5.0,AMAZON_FASHION_5,These NORP
B000V0IBDM ORG
Plantar Fascitis PERSON
3 Days DATE
6th ORDINAL
SmartDestination WORK_OF_ART
one day DATE
years DATE
257lbs CARDINAL
every 3 months DATE
B000V0IBDM ORG
B000V0IBDM ORG
,5.0,AMAZON_FASHION_5,These NORP
Waaaay GPE
two CARDINAL
30 inch QUANTITY
34 CARDINAL
Waaaay GPE
well",5.0,AMAZON_FASHION_5,Typical Quality ORG
first ORDINAL
B000YFSR5G,"Fit GPE
bad,3.0,AMAZON_FASHION_5,Three Stars WORK_OF_ART
four CARDINAL
fit,5.0,AMAZON_FASHION_5,Five CARDINAL
Nice ORG
Nice ORG
30 inch QUANTITY
34 CARDINAL
two CARDINAL
well",5.0,AMAZON_FASHION_5,Typical Quality ORG
first ORDINAL
B000YFSR4W,"Fit GPE
bad,3.0,AMAZON_FASHION_5,Three Stars WORK_OF_ART
four CARDINAL
fit,5.0,A

In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords') # Download the stopwords dataset
nltk.download('wordnet') # Download the wordnet dataset
nltk.download('averaged_perceptron_tagger') # Download the tagger resource.
# Download the english specific resource for the pos_tag function.
nltk.download('averaged_perceptron_tagger_eng') #This is the change.
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# Import wordnet
from nltk.corpus import wordnet
from nltk import pos_tag
import spacy
from sklearn.feature_extraction.text import CountVectorizer

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)
  # Added regex=True for clarity

                                                                                       # and to avoid future warnings


corpus = df["asin,reviewText,overall,category,summary"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.toarray())

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


Mounted at /content/drive
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords') # Download the stopwords dataset
nltk.download('wordnet') # Download the wordnet dataset
nltk.download('averaged_perceptron_tagger') # Download the tagger resource.
# Download the english specific resource for the pos_tag function.
nltk.download('averaged_perceptron_tagger_eng') #This is the change.
import os
import numpy as np
import pandas as pd
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# Import wordnet
from nltk.corpus import wordnet
from nltk import pos_tag
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer

# Mount Google Drive (if running in Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'

# Load the dataframe
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter="\t")

# Convert the column to lowercase
text = df["asin,reviewText,overall,category,summary"].str.lower()

# Remove punctuation
text = df["asin,reviewText,overall,category,summary"].str.translate(str.maketrans("", "", string.punctuation))

# Remove digits
text = df["asin,reviewText,overall,category,summary"].str.replace(r'\d+', '', regex=True)
  # Added regex=True for clarity
corpus = df["asin,reviewText,overall,category,summary"]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.toarray())                                                                                   # and to avoid future warnings



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


Mounted at /content/drive
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# Install necessary libraries
!pip install nltk gensim scikit-learn matplotlib pandas

# Import required libraries
import os
import numpy as np
import pandas as pd
import re
import string
import nltk
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from gensim.models import Word2Vec
from sklearn.manifold import TSNE
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from google.colab import drive

# Download NLTK datasets
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Mount Google Drive (for Colab users)
drive.mount('/content/drive', force_remount=True)

# Define the dataset path
dataset_path = "/content/drive/My Drive/Colab Notebooks/IRS Project/AMAZON_FASHION_5_part0.csv"

# Load dataset
try:
    df = pd.read_csv(dataset_path, encoding='latin1', delimiter="\t", names=['asin', 'reviewText', 'overall', 'category', 'summary'])
    print("✅ Dataset loaded successfully!")
except Exception as e:
    print("❌ Error loading dataset:", e)

# Ensure 'reviewText' is a string before processing
df['reviewText'] = df['reviewText'].astype(str).str.lower()

# Tokenize text
tokenized_texts = [word_tokenize(sentence) for sentence in df["reviewText"]]

# Ensure valid tokenized data
if len(tokenized_texts) == 0:
    raise ValueError("❌ Tokenized text data is empty. Check dataset preprocessing!")

# Train CBOW Model
cbow_model = Word2Vec(sentences=tokenized_texts, vector_size=50, window=5, min_count=2, sg=0)

# Train Skip-gram Model
skipgram_model = Word2Vec(sentences=tokenized_texts, vector_size=50, window=5, min_count=2, sg=1)

# Function to visualize Word2Vec embeddings
def visualize_embeddings(model):
    words = list(model.wv.index_to_key)[:100]  # Limit to first 100 words
    if len(words) < 2:
        print("❌ Not enough words to visualize.")
        return

    vectors = np.array([model.wv[word] for word in words])

    # Set perplexity dynamically (min: 5, max: 30)
    perplexity_value = max(5, min(30, len(words) - 1))

    tsne = TSNE(n_components=2, random_state=42, perplexity=perplexity_value)
    reduced_vectors = tsne.fit_transform(vectors)

    plt.figure(figsize=(10, 6))
    for word, coord in zip(words, reduced_vectors):
        plt.scatter(coord[0], coord[1])
        plt.annotate(word, (coord[0], coord[1]), fontsize=9)

    plt.title("Word Embeddings Visualization")
    plt.show()

# Visualize embeddings
visualize_embeddings(cbow_model)
visualize_embeddings(skipgram_model)

# Train a custom Word2Vec model with tuned hyperparameters
custom_model = Word2Vec(sentences=tokenized_texts, vector_size=100, window=3, min_count=2, sg=1, epochs=20)

# Save and load the model
custom_model.save("custom_word2vec.model")
loaded_model = Word2Vec.load("custom_word2vec.model")

# Test most similar words
try:
    print("Similar to 'fantastic':", loaded_model.wv.most_similar("fantastic"))
except KeyError:
    print("Word 'fantastic' not in vocabulary!")

# Word analogy example
try:
    print("Word analogy (king + woman - man):", loaded_model.wv.most_similar(positive=['king', 'woman'], negative=['man']))
except KeyError:
    print("One or more words missing in vocabulary!")

# Function to convert sentences to vectors
def get_sentence_vector(sentence, model):
    words = word_tokenize(sentence.lower())
    vectors = [model.wv[word] for word in words if word in model.wv]
    return np.mean(vectors, axis=0) if vectors else np.zeros(model.vector_size)

# Convert dataset text into vectors
X = np.array([get_sentence_vector(sent, loaded_model) for sent in df["reviewText"]])

# Prepare classification labels (1 = Positive, 0 = Negative based on rating)
y = df['overall'].apply(lambda x: 1 if x > 3 else 0).to_numpy()

# Ensure compatible shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a classifier (Random Forest)
classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, y_train)

# Evaluate classifier
y_pred = classifier.predict(X_test)
print("✅ Model Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Mounted at /content/drive
✅ Dataset loaded successfully!
❌ Not enough words to visualize.
❌ Not enough words to visualize.
Word 'fantastic' not in vocabulary!
One or more words missing in vocabulary!
Shape of X: (3320, 100)
Shape of y: (3320,)
✅ Model Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       664

    accuracy                           1.00       664
   macro avg       1.00      1.00      1.00       664
weighted avg       1.00      1.00      1.00       664



In [ ]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from textblob import TextBlob

# Install and download necessary NLTK data
import nltk
nltk.download('punkt')
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Load dataset from Google Drive (if using Google Colab)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define the path to the dataset
path = '/content/drive/My Drive/Colab Notebooks/IRS Project/'
# The delimiter is changed to ',' to correctly parse the columns
df = pd.read_csv(path + 'AMAZON_FASHION_5_part0.csv', encoding='latin1', delimiter=",")

# Ensure correct column names (adjust based on actual dataset structure)
df.columns = ['asin', 'reviewText', 'overall', 'category', 'summary']

# Text Preprocessing function
def clean_text(text):
    text = str(text).lower()  # Convert to lowercase
    text = re.sub(r'<.*?>', '', text)  # Remove HTML tags
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Remove punctuation and numbers
    text = ' '.join([word for word in text.split() if word not in stop_words])  # Remove stopwords
    return text

# Apply text cleaning
df['cleaned_review'] = df['reviewText'].apply(clean_text)

# Sentiment Analysis using TextBlob
def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity >= 0.1:
        return 'Positive'
    elif polarity <= -0.1:
        return 'Negative'
    else:
        return 'Neutral'

df['sentiment'] = df['cleaned_review'].apply(get_sentiment)

# Compare sentiment with actual ratings
def map_rating_to_sentiment(rating):
    if rating >= 4:
        return 'Positive'
    elif rating == 3:
        return 'Neutral'
    else:
        return 'Negative'

df['actual_sentiment'] = df['overall'].apply(map_rating_to_sentiment)

# Calculate accuracy
accuracy = (df['sentiment'] == df['actual_sentiment']).mean()
print(f'Sentiment Analysis Accuracy: {accuracy * 100:.2f}%')

# Display sample results
print(df[['reviewText', 'sentiment', 'actual_sentiment']].head())

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Mounted at /content/drive
Sentiment Analysis Accuracy: 75.52%
                                          reviewText sentiment  \
0                           Great product and price!  Positive   
1      Waaay too small. Will use for futur children!  Negative   
2                    Stays vibrant after many washes  Positive   
3                    Stays vibrant after many washes  Positive   
4  My son really likes the pink. Ones which I was...   Neutral   

  actual_sentiment  
0         Positive  
1          Neutral  
2         Positive  
3         Positive  
4         Positive  
